import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync, existsSync} from 'node:fs';
import {createMarkdownProcessor} from '@astrojs/markdown-remark';
import {parseFragment} from 'parse5';
const slug='tomato-powder-hot-cold-break';
for(const lang of ['en','zh']) test(`${lang}: tomato reader and existing food application discovery`,()=>{
 const prefix=lang==='zh'?'zh/':'';
 const html=readFileSync(`dist/${prefix}resources/blog/${slug}/index.html`,'utf8');
 assert.match(html,/tomato-reader/);
 for(const route of ['solutions/food','resources/application-guides'])assert.ok(readFileSync(`dist/${prefix}${route}/index.html`,'utf8').includes(`/${prefix}resources/blog/${slug}`),route);
 assert.ok(html.includes(`href="/${prefix}solutions/food"`));
 assert.ok(html.includes(`href="/${lang==='en'?'zh/':''}resources/blog/${slug}"`));
 assert.ok(!html.includes(lang==='en'?'Interested in our botanical extracts?':'对我们的植物提取物感兴趣？'));
});
const nodes=n=>[n,...(n.childNodes??[]).flatMap(nodes)];
const attr=(n,k)=>n.attrs?.find(a=>a.name===k)?.value;
const text=n=>n.nodeName==='#text'?n.value:(n.childNodes??[]).map(text).join('');
const norm=s=>s.replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/\s+/g,' ').trim();
for(const lang of ['en','zh']) test(`${lang}: tomato approved prose, fractions and every numerical cell preserved`,async()=>{
 const path=`dist/${lang==='zh'?'zh/':''}resources/blog/${slug}/index.html`;
 assert.ok(existsSync(path),'reviewed tomato route missing');
 const approved=readFileSync(`docs/evidence/tomato/corrected.${lang}.md`,'utf8');
 const processor=await createMarkdownProcessor({smartypants:true});
 const expected=parseFragment((await processor.render(approved.replace(/^# .+\n/,'').split('\n## Sources\n')[0])).code);
 const actual=parseFragment(readFileSync(path,'utf8'));
 const all=nodes(actual); const labels=all.filter(n=>attr(n,'class')==='mobile-label');
 assert.equal(labels.length,15);
 assert.ok(labels.every(n=>!attr(n,'aria-hidden')));
 for(const n of labels)n.childNodes=[];
 const txt=norm(text(actual));
 for(const n of nodes(expected).filter(n=>['h2','h3','p','li'].includes(n.nodeName)))assert.ok(txt.includes(norm(text(n))),norm(text(n)));
 const cells=n=>nodes(n).filter(n=>n.nodeName==='table').map(t=>nodes(t).filter(n=>['th','td'].includes(n.nodeName)).map(n=>norm(text(n))));
 assert.deepEqual(cells(actual),cells(expected)); assert.equal(cells(actual).length,1);
 for(const id of ['1','2'])assert.equal(all.filter(n=>attr(n,'id')===`tomato-ref-${id}`).length,1);
 const expectedCitations=[...approved.split('\n## Sources\n')[0].matchAll(/\[(\d+)\]/g)].map(m=>`#tomato-ref-${m[1]}`);
 assert.deepEqual(all.filter(n=>attr(n,'href')?.startsWith('#tomato-ref-')).map(n=>attr(n,'href')),expectedCitations);
 for(const url of approved.match(/https:\/\/[^\s]+/g))assert.ok(all.some(n=>attr(n,'href')===url));
});
